# Generated by Django 4.1.7 on 2023-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_email', models.CharField(max_length=50)),
                ('s_phone', models.CharField(max_length=50)),
                ('s_password', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
