# Generated by Django 4.1.7 on 2023-03-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
                ('m_product', models.CharField(max_length=50)),
                ('m_price', models.CharField(max_length=50)),
                ('m_description', models.CharField(max_length=500)),
                ('m_Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
