# Generated by Django 4.1.7 on 2023-03-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='m_product',
            new_name='m_category',
        ),
    ]
